spring.application.name=reactiveStudentMngSystem

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/studentMngSystem
spring.r2dbc.username=postgres
spring.r2dbc.password=akashk

spring.sql.init.mode=always